#' Get FLIR Data Matrix
#'
#' This function retrieves the data matrix that stores the temperature measurements from a FLIR thermal image generated by a FLIR camera.
#'
#' @param flir_csv_path The path to the FLIR CSV file containing the temperature data.
#'
#' @return A data matrix containing the temperature measurements from the FLIR image, along with the FLIR image ID.
#'
#' @importFrom readr read_delim
#' @importFrom dplyr bind_cols
#'
#' @keywords FLIR data matrix temperature
#'
#' @export
get_flir_data_matrix <- function(flir_csv_path) {
  flir_id <- get_flir_img_id(flir_csv_path = flir_csv_path)
  flir_id <- gsub("\\.jpg$", "", flir_id)

  metadata_row <- grep("Frame 1", flir_csv_path)
  matrix_temp <- flir_csv_path[(metadata_row:length(flir_csv_path))]
  matrix_temp <- gsub("Frame [0-9]{1,}", "", matrix_temp)
  matrix_temp <- gsub("^,|,$|^;|;$", "", matrix_temp)
  matrix_temp <- matrix_temp[nchar(matrix_temp) > 0]
  matrix_temp <- gsub(",|;", "\t", matrix_temp)

  suppressMessages(
    output <- readr::read_delim(paste0(matrix_temp, collapse = "\n"),
                                delim = "\t", col_names = FALSE)
  )

  parameters <- get_flir_parameters(flir_csv_path)
  if (grepl("\\C$", parameters$refl_temp)) {
    message("Temperature measurements are in Celsius")
  } else if (grepl("\\F$", parameters$refl_temp)) {
    message("Temperature measurements are in Fahrenheit")
  }

  return(dplyr::bind_cols(flir_id = flir_id, output))
}
