#' Get FLIR Data Matrix
#'
#' This function retrieves the data matrix that stores the temperature measurements from a FLIR thermal image generated by a FLIR camera.
#'
#' @param fpath The path to the FLIR CSV file containing the temperature data.
#'
#' @return A data matrix containing the temperature measurements from the FLIR image, along with the FLIR image ID.
#'
#' @keywords FLIR data matrix temperature
#'
#' @export
get_flir_data_matrix <- function(fpath) {
  raw_data <- readLines(fpath)
  flir_id <- get_flir_img_id(flir_obj = raw_data)
  flir_id <- gsub(",{2, }$|;{2, }$", "", gsub("\\.jpg", "", flir_id))

  metadata_row <- grep("Frame 1", raw_data)
  matrix_temp <- raw_data[(metadata_row:length(raw_data))]
  matrix_temp <- gsub("Frame [0-9]{1,}", "", matrix_temp)
  matrix_temp <- gsub("^,|,$|^;|;$", "", matrix_temp)
  matrix_temp <- matrix_temp[nchar(matrix_temp) > 0]
  matrix_temp <- gsub(",|;", "\t", matrix_temp)

  suppressMessages(
    output <- readr::read_delim(paste0(matrix_temp, collapse = "\n"),
                                delim = "\t", col_names = FALSE)
  )

parameters <- get_flir_parameters(raw_data)

  if(ncol(parameters) == 1){
    message("Review the scale of measurements.")
  }
  else if(ncol(parameters) >1){
    if (grepl("\\C$", parameters$refl_temp)) {
      message("Temperature measurements are in Celsius")
    }
    else if (grepl("\\F$", parameters$refl_temp)) {
      message("Temperature measurements are in Fahrenheit")
    }
  }
  flir_matrix <- cbind(flir_id = flir_id, output)

  return(flir_matrix)
}
