#' Get FLIR Data Matrix
#'
#' This function retrieves the data matrix that stores the temperature measurements from a FLIR thermal image generated by a FLIR camera.
#'
#' @param file The path to the FLIR CSV file containing the temperature data.
#'
#' @return A data matrix containing the temperature measurements from the FLIR image, along with the FLIR image ID.
#'
#' @keywords FLIR data matrix temperature
#'
#' @export
get_flir_data_matrix <- function(file) {
  raw_data <- readLines(file)

  flir_id <- get_flir_img_id(flir_obj = raw_data)
  metadata_row <- grep("Frame 1", raw_data)
  matrix_temp <- raw_data[(metadata_row:length(raw_data))]
  matrix_temp <- gsub("Frame [0-9]{1,}", "", matrix_temp)
  matrix_temp <- gsub("^,|,$|^;|;$", "", matrix_temp)
  matrix_temp <- matrix_temp[nchar(matrix_temp) > 0]
  matrix_temp <- gsub(",|;", "\t", matrix_temp)

  # Usar fread de data.table para una lectura más eficiente
  output <- data.table::fread(paste0(matrix_temp, collapse = "\n"), sep = "\t", header = FALSE)
  colnames(output) <- paste0("temp_", seq(1:ncol(output)))
  parameters <- get_flir_parameters(raw_data)

  if (ncol(parameters) == 1) {
    message("Review the scale of measurements.")
  } else if (ncol(parameters) > 1) {
    if ("temp_refl" %in% names(parameters)) {

      if(grepl("\\C$", parameters$temp_refl))

        message("Temperature measurements are in Celsius")
      else if(grepl("\\F$", parameters$temp_refl))
        message("Temperature measurements are in Fahrenheit")

    } else if ("refl_temp" %in% names(parameters)) {
      if(grepl("\\C$", parameters$refl_temp))

        message("Temperature measurements are in Celsius")
      else if(grepl("\\F$", parameters$refl_temp))
        message("Temperature measurements are in Fahrenheit")
    }
  }

  if (ncol(parameters) == 1) {
    out_params <- data.frame(flir_id = flir_id)
  } else if(ncol(parameters) > 1){
    out_params <- cbind(flir_id = flir_id,
                        parameters)
  }

  return(cbind(out_params, output))
}
